import type { EadEssayTheme, EadExam, EadLesson, EadPlan, EadQuestion } from "./types";

export const EAD_DISCIPLINES = [
  "Linguagens",
  "Matemática",
  "Ciências Humanas",
  "Ciências da Natureza",
  "Redação",
  "Atualidades",
] as const;

export const DEFAULT_LESSONS: EadLesson[] = [
  {
    id: "lesson-mat-functions",
    title: "Funções: leitura de gráficos e aplicações",
    discipline: "Matemática",
    subject: "Funções",
    module: "Álgebra essencial",
    trail: "Base ENEM",
    level: "intermediario",
    type: "video",
    durationMinutes: 42,
    description: "Domínio, imagem, crescimento, decrescimento e interpretação de gráficos em situações-problema.",
    teacherName: "Equipe Vestibulando",
    videoUrl: "https://www.youtube.com/results?search_query=funcoes+enem+aula",
    materialUrl: "https://download.inep.gov.br/educacao_basica/enem/matriz_referencia.pdf",
    editalReference: "Competência de área 5 — Modelar e resolver problemas",
    published: true,
    builtIn: true,
  },
  {
    id: "lesson-mat-percentage",
    title: "Porcentagem, juros e matemática financeira",
    discipline: "Matemática",
    subject: "Matemática financeira",
    module: "Números e operações",
    trail: "Base ENEM",
    level: "iniciante",
    type: "resumo",
    durationMinutes: 35,
    description: "Estratégias rápidas para porcentagem, descontos, acréscimos e juros simples e compostos.",
    materialUrl: "https://download.inep.gov.br/enem/provas_e_gabaritos/2023_PV_impresso_D2_CD7.pdf",
    editalReference: "Competência de área 1 — Construir significados para os números",
    published: true,
    builtIn: true,
  },
  {
    id: "lesson-languages-interpretation",
    title: "Interpretação textual e gêneros discursivos",
    discipline: "Linguagens",
    subject: "Interpretação de texto",
    module: "Leitura e linguagem",
    trail: "Base ENEM",
    level: "intermediario",
    type: "video",
    durationMinutes: 48,
    description: "Intencionalidade, inferência, ironia, variação linguística e função social dos gêneros.",
    videoUrl: "https://www.youtube.com/results?search_query=interpretacao+de+texto+enem",
    editalReference: "Competência de área 7 — Confrontar opiniões e pontos de vista",
    published: true,
    builtIn: true,
  },
  {
    id: "lesson-humanities-brasil",
    title: "Brasil República: cidadania e transformações sociais",
    discipline: "Ciências Humanas",
    subject: "História do Brasil",
    module: "Brasil contemporâneo",
    trail: "Humanas em contexto",
    level: "intermediario",
    type: "mapa-mental",
    durationMinutes: 40,
    description: "República, industrialização, direitos sociais, democracia e participação política.",
    materialUrl: "https://download.inep.gov.br/enem/provas_e_gabaritos/2023_PV_impresso_D1_CD1.pdf",
    editalReference: "Competência de área 5 — Cidadania e democracia",
    published: true,
    builtIn: true,
  },
  {
    id: "lesson-nature-ecology",
    title: "Ecologia: ciclos, impactos e sustentabilidade",
    discipline: "Ciências da Natureza",
    subject: "Ecologia",
    module: "Vida e ambiente",
    trail: "Natureza aplicada",
    level: "intermediario",
    type: "slides",
    durationMinutes: 45,
    description: "Relações ecológicas, cadeias alimentares, ciclos biogeoquímicos e problemas ambientais.",
    materialUrl: "https://download.inep.gov.br/enem/provas_e_gabaritos/2023_PV_impresso_D2_CD7.pdf",
    editalReference: "Competência de área 3 — Intervenções no ambiente",
    published: true,
    builtIn: true,
  },
  {
    id: "lesson-nature-electricity",
    title: "Eletricidade no cotidiano",
    discipline: "Ciências da Natureza",
    subject: "Eletrodinâmica",
    module: "Energia e tecnologia",
    trail: "Natureza aplicada",
    level: "avancado",
    type: "audio",
    durationMinutes: 32,
    description: "Corrente, tensão, resistência, potência, consumo e segurança elétrica.",
    audioUrl: "https://www.youtube.com/results?search_query=eletrodinamica+enem+resumo",
    editalReference: "Competência de área 2 — Tecnologias associadas às ciências naturais",
    published: true,
    builtIn: true,
  },
  {
    id: "lesson-essay-structure",
    title: "Estrutura da redação nota 1000",
    discipline: "Redação",
    subject: "Estrutura dissertativo-argumentativa",
    module: "Fundamentos da redação",
    trail: "Redação 900+",
    level: "iniciante",
    type: "video",
    durationMinutes: 55,
    description: "Tese, projeto de texto, desenvolvimento, repertório e proposta de intervenção completa.",
    videoUrl: "https://www.youtube.com/results?search_query=redacao+enem+estrutura+nota+1000",
    materialUrl: "https://download.inep.gov.br/publicacoes/institucionais/avaliacoes_e_exames_da_educacao_basica/a_redacao_no_enem_2023_cartilha_do_participante.pdf",
    editalReference: "Cinco competências da redação do ENEM",
    published: true,
    builtIn: true,
  },
  {
    id: "lesson-current-ai",
    title: "Inteligência artificial, trabalho e cidadania",
    discipline: "Atualidades",
    subject: "Tecnologia e sociedade",
    module: "Debates contemporâneos",
    trail: "Atualidades para prova e redação",
    level: "intermediario",
    type: "resumo",
    durationMinutes: 28,
    description: "Impactos sociais da automação, vieses algorítmicos, educação midiática e regulação.",
    published: true,
    builtIn: true,
  },
];

export const DEFAULT_QUESTIONS: EadQuestion[] = [
  {
    id: "q-mat-001",
    statement: "Uma loja oferece 20% de desconto em um produto de R$ 250,00. O preço final é:",
    discipline: "Matemática",
    subject: "Porcentagem",
    year: 2023,
    board: "Modelo ENEM",
    difficulty: "facil",
    alternatives: ["R$ 180,00", "R$ 190,00", "R$ 200,00", "R$ 210,00", "R$ 220,00"],
    correctIndex: 2,
    explanation: "20% de 250 é 50. Subtraindo o desconto: 250 − 50 = 200.",
    published: true,
    builtIn: true,
  },
  {
    id: "q-mat-002",
    statement: "Uma função afim passa pelos pontos (0, 2) e (3, 11). Qual é sua lei de formação?",
    discipline: "Matemática",
    subject: "Funções",
    year: 2022,
    board: "Modelo ENEM",
    difficulty: "media",
    alternatives: ["f(x)=2x+3", "f(x)=3x+2", "f(x)=3x−2", "f(x)=2x+2", "f(x)=x+2"],
    correctIndex: 1,
    explanation: "O coeficiente angular é (11−2)/(3−0)=3 e o termo independente é f(0)=2.",
    published: true,
    builtIn: true,
  },
  {
    id: "q-lang-001",
    statement: "Em um anúncio publicitário, o uso de uma pergunta direta ao leitor tem como principal efeito:",
    discipline: "Linguagens",
    subject: "Funções da linguagem",
    year: 2021,
    board: "Modelo ENEM",
    difficulty: "media",
    alternatives: [
      "Apagar a presença do interlocutor",
      "Estabelecer interlocução e estimular uma resposta",
      "Eliminar a intenção persuasiva",
      "Tornar o texto exclusivamente científico",
      "Impedir diferentes interpretações",
    ],
    correctIndex: 1,
    explanation: "A pergunta aproxima o enunciador do leitor e ativa a função conativa, comum na publicidade.",
    published: true,
    builtIn: true,
  },
  {
    id: "q-human-001",
    statement: "A Constituição brasileira de 1988 ficou conhecida como Constituição Cidadã principalmente por:",
    discipline: "Ciências Humanas",
    subject: "Cidadania",
    year: 2020,
    board: "ENEM adaptada",
    difficulty: "facil",
    alternatives: [
      "Restringir direitos políticos",
      "Restaurar o voto censitário",
      "Ampliar direitos civis, sociais e políticos",
      "Eliminar a separação dos poderes",
      "Proibir a organização sindical",
    ],
    correctIndex: 2,
    explanation: "O texto constitucional consolidou a redemocratização e ampliou garantias individuais e sociais.",
    published: true,
    builtIn: true,
  },
  {
    id: "q-nature-001",
    statement: "Em uma cadeia alimentar, a redução intensa de predadores de topo tende inicialmente a:",
    discipline: "Ciências da Natureza",
    subject: "Ecologia",
    year: 2023,
    board: "Modelo ENEM",
    difficulty: "media",
    alternatives: [
      "Reduzir todas as populações",
      "Aumentar as presas desses predadores",
      "Eliminar os produtores",
      "Impedir a fotossíntese",
      "Diminuir a energia solar disponível",
    ],
    correctIndex: 1,
    explanation: "Com menor pressão de predação, a população das presas tende a aumentar, provocando efeito em cascata.",
    published: true,
    builtIn: true,
  },
  {
    id: "q-nature-002",
    statement: "Um aparelho de 1 000 W funciona por 2 horas. A energia consumida é:",
    discipline: "Ciências da Natureza",
    subject: "Eletricidade",
    year: 2022,
    board: "Modelo ENEM",
    difficulty: "facil",
    alternatives: ["0,5 kWh", "1 kWh", "2 kWh", "10 kWh", "20 kWh"],
    correctIndex: 2,
    explanation: "1 000 W = 1 kW. Energia = potência × tempo = 1 kW × 2 h = 2 kWh.",
    published: true,
    builtIn: true,
  },
  {
    id: "q-current-001",
    statement: "A educação midiática contribui para a cidadania digital porque ajuda o usuário a:",
    discipline: "Atualidades",
    subject: "Tecnologia e sociedade",
    year: 2024,
    board: "Interdisciplinar",
    difficulty: "media",
    alternatives: [
      "Compartilhar toda mensagem recebida",
      "Reconhecer fontes, evidências e estratégias de manipulação",
      "Substituir jornalistas por algoritmos",
      "Evitar qualquer participação política",
      "Eliminar divergências de opinião",
    ],
    correctIndex: 1,
    explanation: "A leitura crítica de fontes e evidências reduz a circulação de desinformação e melhora a participação pública.",
    published: true,
    builtIn: true,
  },
  {
    id: "q-essay-001",
    statement: "Na proposta de intervenção do ENEM, qual conjunto contempla os elementos fundamentais?",
    discipline: "Redação",
    subject: "Proposta de intervenção",
    year: 2024,
    board: "Modelo ENEM",
    difficulty: "media",
    alternatives: [
      "Tema, título e assinatura",
      "Agente, ação, meio, finalidade e detalhamento",
      "Citação, repertório e pergunta",
      "Causa, consequência e contra-argumento",
      "Introdução, narração e clímax",
    ],
    correctIndex: 1,
    explanation: "Uma proposta completa identifica quem agirá, o que fará, como, para quê e apresenta detalhamento.",
    published: true,
    builtIn: true,
  },
];

export const DEFAULT_EXAMS: EadExam[] = [
  {
    id: "exam-diagnostic",
    title: "Diagnóstico inicial",
    description: "Simulado curto para identificar os assuntos que precisam entrar primeiro no seu plano.",
    type: "completo",
    durationMinutes: 25,
    questionIds: DEFAULT_QUESTIONS.map((question) => question.id),
    questionCount: DEFAULT_QUESTIONS.length,
    rankingEnabled: false,
    published: true,
    builtIn: true,
  },
  {
    id: "exam-enem-day-1",
    title: "Mini ENEM — Dia 1",
    description: "Linguagens, Ciências Humanas, Atualidades e Redação em formato reduzido.",
    type: "enem-dia-1",
    durationMinutes: 35,
    questionIds: ["q-lang-001", "q-human-001", "q-current-001", "q-essay-001"],
    questionCount: 4,
    rankingEnabled: true,
    published: true,
    builtIn: true,
  },
  {
    id: "exam-enem-day-2",
    title: "Mini ENEM — Dia 2",
    description: "Matemática e Ciências da Natureza com cronômetro e correção comentada.",
    type: "enem-dia-2",
    durationMinutes: 35,
    questionIds: ["q-mat-001", "q-mat-002", "q-nature-001", "q-nature-002"],
    questionCount: 4,
    rankingEnabled: true,
    published: true,
    builtIn: true,
  },
];

export const DEFAULT_ESSAY_THEMES: EadEssayTheme[] = [
  {
    id: "essay-digital-citizenship",
    title: "Desafios para a formação da cidadania digital no Brasil",
    description: "Discuta os obstáculos para o uso crítico, responsável e inclusivo das tecnologias digitais.",
    supportingTexts: [
      "O acesso à informação não garante, sozinho, capacidade de verificar fontes e reconhecer manipulações.",
      "Desigualdades de conectividade e formação ampliam a distância entre diferentes grupos sociais.",
      "Escola, família, plataformas e poder público compartilham responsabilidades na construção da cidadania digital.",
    ],
    tags: ["tecnologia", "educação", "cidadania"],
    published: true,
    builtIn: true,
  },
  {
    id: "essay-mental-health",
    title: "Caminhos para promover saúde mental entre jovens brasileiros",
    description: "Analise causas, consequências e possíveis intervenções sociais para o cuidado com a saúde mental.",
    supportingTexts: [
      "A adolescência reúne transformações físicas, sociais e emocionais que exigem redes de apoio.",
      "Preconceito e falta de informação ainda dificultam a busca por atendimento qualificado.",
      "A promoção de saúde mental depende de prevenção, acolhimento e acesso a serviços.",
    ],
    tags: ["saúde", "juventude", "políticas públicas"],
    published: true,
    builtIn: true,
  },
];

export const DEFAULT_PLANS: EadPlan[] = [
  {
    id: "plan-essential",
    name: "Preparatório Essencial",
    price: 39.9,
    period: "mensal",
    description: "Acesso às trilhas, questões, simulados e plano de estudos.",
    features: ["Conteúdo completo", "Banco de questões", "Simulados", "Plano personalizado"],
    active: true,
  },
  {
    id: "plan-complete",
    name: "Preparatório Completo",
    price: 69.9,
    period: "mensal",
    description: "Inclui redação, aulas ao vivo e plantão de dúvidas.",
    features: ["Todos os recursos", "Correção de redação", "Aulas ao vivo", "Plantão de dúvidas"],
    active: true,
  },
];

export const DEFAULT_FAQS = [
  {
    question: "Como o plano de estudos é criado?",
    answer: "Informe sua prova, data, nível e horas disponíveis. O sistema distribui aulas, questões, revisões e simulados até a prova.",
  },
  {
    question: "Meu progresso é salvo automaticamente?",
    answer: "Sim. Aulas, respostas, simulados e redações são salvos na sua conta. Rascunhos também ficam protegidos durante a digitação.",
  },
  {
    question: "Como funciona a correção de redação?",
    answer: "Envie o texto digitado ou uma foto. O professor avalia as cinco competências, registra comentários e devolve a nota e orientações.",
  },
  {
    question: "Posso estudar pelo celular?",
    answer: "Sim. O portal é responsivo, tem modo de baixo consumo e permite marcar materiais compatíveis para uso posterior.",
  },
  {
    question: "Onde tiro dúvidas?",
    answer: "Use o chat protegido, o fórum da disciplina ou consulte os horários do plantão de dúvidas.",
  },
];

export const BRAZILIAN_EXAMS = [
  "ENEM",
  "Vestibular UFG",
  "Vestibular UnB",
  "Vestibular USP/Fuvest",
  "Vestibular Unicamp",
  "Concurso público",
  "Reforço escolar",
];
